drive:
    freq_hertz: 1
    verbose: True
    verbosity: 1
parts:
  - mock:
      type: MockMode
  - camera:
      type: PiCam
      arguments:
        colormode: RGB
  - joystick:
      type: PS3Robotics