drive:
    freq_hertz: 20
    verbose: True
    verbosity: 20
parts:
  - mock:
      type: MockMode
  - camera:
      type: PiCam
      arguments:
        colormode: RGB
  - joystick:
      type: PS3Robotics
  - arduino_pwm_motors:
      type: Stepper
      arguments:
        bus_addr: 0x8
        device: 1
  - arduino_pwm_motors:
      type: Servo
      arguments:
        bus_addr: 0x8
        device: 1