drive:
    freq_hertz: 20
    verbose: True
    verbosity: 20
parts:
  - mock:
      type: MockMode
  - still_camera:
      type: StillCam
      arguments:
        resolution: !!python/tuple [500,500]
  - joystick:
      type: PS3Robotics
  - arduino_pwm_motors:
      type: MotorControl
      arguments:
        bus_addr: 0x8
        device: 1
#  - arduino_pwm_motors:
#      type: Servo
#      arguments:
#        bus_addr: 0x8
#        device: 1