drive:
    freq_hertz: 10

parts:
    - actuator:
    
        type: SteeringController
        arguments:
        channel: 1
        full_left_pulse:    490
        full_right_pulse:   290
        
        type: ThrottleController
        channel: 1
        full_reverse_pulse:     290
        full_forward_pulse:     490
        neutral_pulse:          390
        
    - camera: 
        type: WebCam
        
    - display:
        type: DisplayFeed
        arguments:
        window_name: 'MuleView'
        

        STEERING:
    STEERING_CHANNEL : 1
    STEERING_LEFT_PWM : 420
    STEERING_RIGHT_PWM : 360

THROTTLE:
    THROTTLE_CHANNEL : 0
    THROTTLE_FORWARD_PWM : 400
    THROTTLE_STOPPED_PWM : 360
    THROTTLE_REVERSE_PWM : 310
