drive:
    freq_hertz: 10

parts:
 - actuator:
        type: SteeringController
        arguments:
          channel: 1
          full_left_pulse:    490
          full_right_pulse:   290
 - actuator:
        type: ThrottleController
        arguments:
          channel: 1
          full_reverse_pulse:     290
          full_forward_pulse:     490
          neutral_pulse:          390
 - camera: 
        type: WebCam
        
 - display:
        type: DisplayFeed
        arguments:
        window_name: 'MuleView'