drive:
    freq_hertz: 10

parts:
 - joystick:
      type: PS3Controller
 
 - led: 
      type: sequential_LED_loop
      arguments:
        PIN_BLUE1: 26
        PIN_BLUE2: 19
        PIN_BLUE3: 13
        PIN_BLUE4: 6
 - actuator:
        type: SteeringController
        arguments:
          controller: PCA
          channel: 1
          full_left_pulse:    425
          full_right_pulse:   295
 - actuator:
        type: ThrottleController
        arguments:
          controller: PCA
          channel: 1
          full_reverse_pulse:     350
          full_forward_pulse:     385
          neutral_pulse:          370
 - camera: 
        type: PiCam
